name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: |
        echo "=== 빌드 시작 ==="
        echo "Repository: ${{ github.repository }}"
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "=== 의존성 확인 ==="
        npm list --depth=0
        echo "=== 빌드 실행 ==="
        npm run build
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
      
    - name: Check build output
      run: |
        echo "=== 빌드 결과물 확인 ==="
        ls -la dist/
        echo "=== 파일 개수 ==="
        find dist -type f | wc -l
        echo "=== 빌드 완료 ==="
      
    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: # 커스텀 도메인이 있다면 여기에 입력
