name: Deploy to GitHub Pages (Direct) - Disabled

# 이 워크플로우는 비활성화되었습니다. deploy-gh-pages.yml을 사용하세요.
on:
  workflow_dispatch: # 수동 실행만 가능

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Prepare for deployment
      run: |
        # 빌드 결과물 확인
        echo "=== 빌드 결과물 확인 ==="
        ls -la dist/
        echo "=== 파일 크기 ==="
        du -sh dist/
        echo "=== 파일 개수 ==="
        find dist -type f | wc -l
        
        # 심볼릭 링크 확인 및 제거
        echo "=== 심볼릭 링크 확인 ==="
        find dist -type l -ls || echo "심볼릭 링크 없음"
        find dist -type l -delete || echo "심볼릭 링크 제거 완료"
        
        # 빈 디렉토리 제거
        find dist -type d -empty -delete || echo "빈 디렉토리 제거 완료"
        
        # 최종 확인
        echo "=== 최종 빌드 결과물 ==="
        ls -la dist/
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: dist
